M48
; DRILL file KiCad 10.0.1 date 2026-09-11T15:42:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-11T15:42:22+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C6.500
%
G90
G05
T1
X150.0Y-60.0
T3
X150.0Y-74.5
T2
X108.45Y-97.6G85X110.95Y-97.6
G05
X189.05Y-97.6G85X191.55Y-97.6
G05
M30
